//! Outbound model-control golden cases generated by executing the reference's
//! buildThinkingFields, extractThinkingSchema, and inferenceConfig builder at
//! chaogei/Kiro-account-manager commit 447adcdb468157312621b1f09448278bd9bca748.
//! Only those inspected pure helpers ran; no upstream requests were made.

use kproxy_translate::{
    claude_to_kiro, openai_to_kiro, validate_claude, validate_openai, ClaudeRequest, OpenAiRequest,
    TranslationOptions,
};
use serde_json::{json, Value};

// JSON 0 and 0.0 mean the same thing on the wire. Normalize numeric notation
// without weakening object-key, field-presence, or string comparisons.
fn canonical(value: &Value) -> Value {
    match value {
        Value::Number(number) => json!(number.as_f64().expect("finite fixture number")),
        Value::Array(values) => Value::Array(values.iter().map(canonical).collect()),
        Value::Object(values) => Value::Object(
            values
                .iter()
                .map(|(key, value)| (key.clone(), canonical(value)))
                .collect(),
        ),
        other => other.clone(),
    }
}

#[test]
fn outbound_model_controls_match_pinned_chaogei_reference() {
    let fixture: Value = serde_json::from_str(include_str!("fixtures/chaogei_model_controls.json"))
        .expect("reference fixture");
    assert_eq!(
        fixture["referenceCommit"],
        "447adcdb468157312621b1f09448278bd9bca748"
    );
    for case in fixture["cases"].as_array().expect("cases") {
        let name = case["name"].as_str().expect("case name");
        let mut options = TranslationOptions::new("claude-sonnet-4.6", "AI_EDITOR");
        options.additional_model_request_fields_schema =
            (!case["schema"].is_null()).then(|| case["schema"].clone());
        let payload = match case["protocol"].as_str().expect("protocol") {
            "claude" => {
                let request: ClaudeRequest =
                    serde_json::from_value(case["request"].clone()).unwrap();
                validate_claude(&request).unwrap_or_else(|error| panic!("{name}: {error}"));
                claude_to_kiro(&request, &options)
            }
            "openai" => {
                let request: OpenAiRequest =
                    serde_json::from_value(case["request"].clone()).unwrap();
                validate_openai(&request).unwrap_or_else(|error| panic!("{name}: {error}"));
                openai_to_kiro(&request, &options)
            }
            other => panic!("unexpected fixture protocol: {other}"),
        };
        let wire = serde_json::to_value(payload).unwrap();
        assert_eq!(
            canonical(&wire["inferenceConfig"]),
            canonical(&case["expectedInference"]),
            "{name}: inferenceConfig"
        );
        assert_eq!(
            canonical(&wire["additionalModelRequestFields"]),
            canonical(&case["expectedAdditional"]),
            "{name}: additionalModelRequestFields"
        );
        assert!(
            wire.get("modelRequestIntent").is_none(),
            "{name}: local intent leaked"
        );
    }
}
